# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83d587d5b5fd1cc6a1b040458122f6d9464eb26987dc827723e98f760e22ad36868c9ece7a4bdb474e2360bd6ccbab686c0de94131807ad2f80524b34b9c8dd5

test:
  secret_key_base: 68c1ade1cb1aef8bf9d13c9aa18978b13616bf15845600cfb07340e6919a36eafbee6010e0811d6023c643f156df0a64524e098ce7aa809c1e408580906219b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
